// Here are necessary include headers for using HKCV library

#ifndef _HKCV_PCH_H_
#define _HKCV_PCH_H_

// TODO: reference additional headers your program requires here
/**
*	@brief Header files for the C++ utility library
*/
#include <cassert>
#include <utility>

/**
*	@brief Header files for the STL library
*/
#include <iostream>
#include <fstream>
#include <vector>
#include <string>
#include <cmath>
#include <algorithm>
using namespace std;

/**
*	@brief Header files for OpenCV library 2.4.0
*/
/// Disable warnings generated by OpenCV
/// 'cv::XXXX' : function compiled as native
#pragma warning( disable:4793 )
#include <OpenCV2\opencv.hpp>
#ifdef NDEBUG
#pragma comment( lib, "opencv_core240.lib" )
#pragma message( "Link with opencv_core240.lib." )
#pragma comment( lib, "opencv_imgproc240.lib" )
#pragma message( "Link with opencv_imgproc240.lib." )
#pragma comment( lib, "opencv_highgui240.lib" )
#pragma message( "Link with opencv_highgui240.lib." )
#pragma comment( lib, "opencv_video240.lib" )
#pragma message( "Link with opencv_video240.lib." )
#pragma comment( lib, "opencv_features2d240.lib" )
#pragma message( "Link with opencv_features2d240.lib." )
#pragma comment( lib, "opencv_objdetect240.lib" )
#pragma message( "Link with opencv_objdetect240.lib." )
//#pragma comment( lib, "opencv_ml240.lib" )
//#pragma message( "Link with opencv_ml240.lib." )
//#pragma comment( lib, "opencv_calib3d240.lib" )
//#pragma message( "Link with opencv_calib3d240.lib." )
//#pragma comment( lib, "opencv_contrib240.lib" )
//#pragma message( "Link with opencv_contrib240.lib." )
//#pragma comment( lib, "opencv_legacy240.lib" )
//#pragma message( "Link with opencv_legacy240.lib." )
//#pragma comment( lib, "opencv_flann240.lib" )
//#pragma message( "Link with opencv_flann240.lib." )
#else
#pragma comment( lib, "opencv_core240d.lib" )
#pragma message( "Link with opencv_core240d.lib." )
#pragma comment( lib, "opencv_imgproc240d.lib" )
#pragma message( "Link with opencv_imgproc240d.lib." )
#pragma comment( lib, "opencv_highgui240d.lib" )
#pragma message( "Link with opencv_highgui240d.lib." )
#pragma comment( lib, "opencv_video240d.lib" )
#pragma message( "Link with opencv_video240d.lib." )
#pragma comment( lib, "opencv_features2d240d.lib" )
#pragma message( "Link with opencv_features2d240d.lib." )
#pragma comment( lib, "opencv_objdetect240d.lib" )
#pragma message( "Link with opencv_objdetect240d.lib." )
//#pragma comment( lib, "opencv_ml240d.lib" )
//#pragma message( "Link with opencv_ml240d.lib." )
//#pragma comment( lib, "opencv_calib3d240d.lib" )
//#pragma message( "Link with opencv_calib3d240d.lib." )
//#pragma comment( lib, "opencv_contrib240d.lib" )
//#pragma message( "Link with opencv_contrib240d.lib." )
//#pragma comment( lib, "opencv_legacy240d.lib" )
//#pragma message( "Link with opencv_legacy240d.lib." )
//#pragma comment( lib, "opencv_flann240d.lib" )
//#pragma message( "Link with opencv_flann240d.lib." )
#endif

/**
*	@brief Header file for the MATLAB Engine (if you need HKCV_MATLAB.h)
*/
#ifdef _CHAR16T
#define CHAR16_T
#endif
#include <Engine.h>
#pragma comment( lib , "libeng.lib" )
#pragma message( "Link with libeng.lib" )
#pragma comment( lib , "libmx.lib" )
#pragma message( "Link with libmx.lib" )
#pragma comment( lib , "libmex.lib" )
#pragma message( "Link with libmex.lib" )

/**
*	@brief Header files for Hung-Kuo's Computer Vision Library
*/
#include <HKCV.h>
#include <EdgeLinking/HKEdgeLinking.h>
#include <ImageThinning/HKImgThinning.h>
#include <GrabCut/HKGrabCut.h>
#include <PatchMatch/HKPatchMatch.h>
#include <Saliency/HKSaliency.h>
#include <ColorTransfer/HKColorTransfer.h>
#include <ImageMatting/HKImgMatting.h>

#endif