//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : BezierCurve.h
//  @ Date : 2011/9/3
//  @ Author :
//
//


#if !defined(_BEZIERCURVE_H)
#define _BEZIERCURVE_H

#include "PathInterpolater.h"

class BezierCurve : public PathInterpolater
{
public:
	Vector2 GetValue(double time);
	inline Vector2 CalcBezierCurvePos(const Vector2& start, const Vector2& cnt1,
	                                  const Vector2& cnt2, const Vector2& end, double Scalar)
	{
		Vector2 out = start * (1.0f - Scalar) * (1.0f - Scalar) * (1.0f - Scalar) +
		              cnt1 * 3.0f * Scalar * (1.0f - Scalar) * (1.0f - Scalar) +
		              cnt2 * 3.0f * Scalar * Scalar * (1.0f - Scalar) +
		              end * Scalar * Scalar * Scalar;
		return out;
	}
};

#endif  //_BEZIERCURVE_H
