//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : HSplineCurve.h
//  @ Date : 2011/9/3
//  @ Author : 
//
//


#if !defined(_HSPLINECURVE_H)
#define _HSPLINECURVE_H

#include "PathInterpolater.h"

class HSplineCurve : public PathInterpolater
{
public:
	Vector2 GetValue(double time);
	static Vector2 CalcHSplineCurvePos(const Vector2& p4, const Vector2& p3,
		const Vector2& p2, const Vector2& p1, double Scalar, double c = 1.7f)
	{
		double S2 = Scalar*Scalar, S3 = Scalar*Scalar*Scalar,tension = (1.0f-c)/2;
		Vector2 start = p2, end = p3, cnt1 = (p1-p3)*tension, cnt2 = (p2-p4)*tension;
		Vector2 out = (start * (-2.0f*S3 + 3.0f *S2) +
			end * (2.0f*S3 -  3.0f *S2 + 1) +
			cnt1 * (S3 - S2) +
			cnt2 * (S3 - 2*S2 + Scalar));
		return out;
	}
};

#endif  //_HSPLINECURVE_H
