//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : LinearLine.h
//  @ Date : 2011/9/3
//  @ Author :
//
//


#if !defined(_LINEARLINE_H)
#define _LINEARLINE_H

#include "PathInterpolater.h"

class LinearLine : public PathInterpolater
{
public:
	Vector2 GetValue(double time);
	static Vector2 CalcStraightPos(const Vector2& p1, const Vector2& p2,
	                               double scalar)
	{
		Vector2 out = p1 * (1.0f - scalar) + p2 * scalar;
		return out;
	}
};

#endif  //_LINEARLINE_H
